// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/google/uuid"
)

type Artist struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Followers int64
}

type User struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Password string
}
